/* Lua の公開関数一覧。
 *
 * このヘッダーは意図的に include guard を持たない。インクルード元で
 * MOCK_LUA_RET と MOCK_LUA_VOID を定義し、宣言、実装、テストを同じ一覧から生成する。
 */

#ifndef MOCK_LUA_RET
    #error MOCK_LUA_RET must be defined before including mock_lua_api_table.h
#endif
#ifndef MOCK_LUA_VOID
    #error MOCK_LUA_VOID must be defined before including mock_lua_api_table.h
#endif

MOCK_LUA_VOID(void, luaL_addgsub, (luaL_Buffer * b, const char *s, const char *p, const char *r), (b, s, p, r),
              (_, _, _, _))
MOCK_LUA_VOID(void, luaL_addlstring, (luaL_Buffer * B, const char *s, size_t l), (B, s, l), (_, _, _))
MOCK_LUA_VOID(void, luaL_addstring, (luaL_Buffer * B, const char *s), (B, s), (_, _))
MOCK_LUA_VOID(void, luaL_addvalue, (luaL_Buffer * B), (B), (_))
MOCK_LUA_RET(void *, luaL_alloc, (void *ud, void *ptr, size_t osize, size_t nsize), (ud, ptr, osize, nsize),
             (_, _, _, _))
MOCK_LUA_RET(int, luaL_argerror, (lua_State * L, int arg, const char *extramsg), (L, arg, extramsg), (_, _, _))
MOCK_LUA_VOID(void, luaL_buffinit, (lua_State * L, luaL_Buffer *B), (L, B), (_, _))
MOCK_LUA_RET(char *, luaL_buffinitsize, (lua_State * L, luaL_Buffer *B, size_t sz), (L, B, sz), (_, _, _))
MOCK_LUA_RET(int, luaL_callmeta, (lua_State * L, int obj, const char *e), (L, obj, e), (_, _, _))
MOCK_LUA_VOID(void, luaL_checkany, (lua_State * L, int arg), (L, arg), (_, _))
MOCK_LUA_RET(lua_Integer, luaL_checkinteger, (lua_State * L, int arg), (L, arg), (_, _))
MOCK_LUA_RET(const char *, luaL_checklstring, (lua_State * L, int arg, size_t *l), (L, arg, l), (_, _, _))
MOCK_LUA_RET(lua_Number, luaL_checknumber, (lua_State * L, int arg), (L, arg), (_, _))
MOCK_LUA_RET(int, luaL_checkoption, (lua_State * L, int arg, const char *def, const char *const lst[]),
             (L, arg, def, lst), (_, _, _, _))
MOCK_LUA_VOID(void, luaL_checkstack, (lua_State * L, int sz, const char *msg), (L, sz, msg), (_, _, _))
MOCK_LUA_VOID(void, luaL_checktype, (lua_State * L, int arg, int t), (L, arg, t), (_, _, _))
MOCK_LUA_RET(void *, luaL_checkudata, (lua_State * L, int ud, const char *tname), (L, ud, tname), (_, _, _))
MOCK_LUA_VOID(void, luaL_checkversion_, (lua_State * L, lua_Number ver, size_t sz), (L, ver, sz), (_, _, _))
MOCK_LUA_RET(int, luaL_execresult, (lua_State * L, int stat), (L, stat), (_, _))
MOCK_LUA_RET(int, luaL_fileresult, (lua_State * L, int stat, const char *fname), (L, stat, fname), (_, _, _))
MOCK_LUA_RET(int, luaL_getmetafield, (lua_State * L, int obj, const char *e), (L, obj, e), (_, _, _))
MOCK_LUA_RET(int, luaL_getsubtable, (lua_State * L, int idx, const char *fname), (L, idx, fname), (_, _, _))
MOCK_LUA_RET(const char *, luaL_gsub, (lua_State * L, const char *s, const char *p, const char *r), (L, s, p, r),
             (_, _, _, _))
MOCK_LUA_RET(lua_Integer, luaL_len, (lua_State * L, int idx), (L, idx), (_, _))
MOCK_LUA_RET(int, luaL_loadbufferx, (lua_State * L, const char *buff, size_t sz, const char *name, const char *mode),
             (L, buff, sz, name, mode), (_, _, _, _, _))
MOCK_LUA_RET(int, luaL_loadfilex, (lua_State * L, const char *filename, const char *mode), (L, filename, mode),
             (_, _, _))
MOCK_LUA_RET(int, luaL_loadstring, (lua_State * L, const char *s), (L, s), (_, _))
MOCK_LUA_RET(unsigned, luaL_makeseed, (lua_State * L), (L), (_))
MOCK_LUA_RET(int, luaL_newmetatable, (lua_State * L, const char *tname), (L, tname), (_, _))
MOCK_LUA_RET(lua_State *, luaL_newstate, (), (), ())
MOCK_LUA_VOID(void, luaL_openselectedlibs, (lua_State * L, int load, int preload), (L, load, preload), (_, _, _))
MOCK_LUA_RET(lua_Integer, luaL_optinteger, (lua_State * L, int arg, lua_Integer def), (L, arg, def), (_, _, _))
MOCK_LUA_RET(const char *, luaL_optlstring, (lua_State * L, int arg, const char *def, size_t *l), (L, arg, def, l),
             (_, _, _, _))
MOCK_LUA_RET(lua_Number, luaL_optnumber, (lua_State * L, int arg, lua_Number def), (L, arg, def), (_, _, _))
MOCK_LUA_RET(char *, luaL_prepbuffsize, (luaL_Buffer * B, size_t sz), (B, sz), (_, _))
MOCK_LUA_VOID(void, luaL_pushresult, (luaL_Buffer * B), (B), (_))
MOCK_LUA_VOID(void, luaL_pushresultsize, (luaL_Buffer * B, size_t sz), (B, sz), (_, _))
MOCK_LUA_RET(int, luaL_ref, (lua_State * L, int t), (L, t), (_, _))
MOCK_LUA_VOID(void, luaL_requiref, (lua_State * L, const char *modname, lua_CFunction openf, int glb),
              (L, modname, openf, glb), (_, _, _, _))
MOCK_LUA_VOID(void, luaL_setfuncs, (lua_State * L, const luaL_Reg *l, int nup), (L, l, nup), (_, _, _))
MOCK_LUA_VOID(void, luaL_setmetatable, (lua_State * L, const char *tname), (L, tname), (_, _))
MOCK_LUA_RET(void *, luaL_testudata, (lua_State * L, int ud, const char *tname), (L, ud, tname), (_, _, _))
MOCK_LUA_RET(const char *, luaL_tolstring, (lua_State * L, int idx, size_t *len), (L, idx, len), (_, _, _))
MOCK_LUA_VOID(void, luaL_traceback, (lua_State * L, lua_State *L1, const char *msg, int level), (L, L1, msg, level),
              (_, _, _, _))
MOCK_LUA_RET(int, luaL_typeerror, (lua_State * L, int arg, const char *tname), (L, arg, tname), (_, _, _))
MOCK_LUA_VOID(void, luaL_unref, (lua_State * L, int t, int ref), (L, t, ref), (_, _, _))
MOCK_LUA_VOID(void, luaL_where, (lua_State * L, int lvl), (L, lvl), (_, _))
MOCK_LUA_RET(int, lua_absindex, (lua_State * L, int idx), (L, idx), (_, _))
MOCK_LUA_VOID(void, lua_arith, (lua_State * L, int op), (L, op), (_, _))
MOCK_LUA_RET(lua_CFunction, lua_atpanic, (lua_State * L, lua_CFunction panicf), (L, panicf), (_, _))
MOCK_LUA_VOID(void, lua_callk, (lua_State * L, int nargs, int nresults, lua_KContext ctx, lua_KFunction k),
              (L, nargs, nresults, ctx, k), (_, _, _, _, _))
MOCK_LUA_RET(int, lua_checkstack, (lua_State * L, int n), (L, n), (_, _))
MOCK_LUA_VOID(void, lua_close, (lua_State * L), (L), (_))
MOCK_LUA_VOID(void, lua_closeslot, (lua_State * L, int idx), (L, idx), (_, _))
MOCK_LUA_RET(int, lua_closethread, (lua_State * L, lua_State *from), (L, from), (_, _))
MOCK_LUA_RET(int, lua_compare, (lua_State * L, int idx1, int idx2, int op), (L, idx1, idx2, op), (_, _, _, _))
MOCK_LUA_VOID(void, lua_concat, (lua_State * L, int n), (L, n), (_, _))
MOCK_LUA_VOID(void, lua_copy, (lua_State * L, int fromidx, int toidx), (L, fromidx, toidx), (_, _, _))
MOCK_LUA_VOID(void, lua_createtable, (lua_State * L, int narr, int nrec), (L, narr, nrec), (_, _, _))
MOCK_LUA_RET(int, lua_dump, (lua_State * L, lua_Writer writer, void *data, int strip), (L, writer, data, strip),
             (_, _, _, _))
MOCK_LUA_RET(int, lua_error, (lua_State * L), (L), (_))
MOCK_LUA_RET(lua_Alloc, lua_getallocf, (lua_State * L, void **ud), (L, ud), (_, _))
MOCK_LUA_RET(int, lua_getfield, (lua_State * L, int idx, const char *k), (L, idx, k), (_, _, _))
MOCK_LUA_RET(int, lua_getglobal, (lua_State * L, const char *name), (L, name), (_, _))
MOCK_LUA_RET(lua_Hook, lua_gethook, (lua_State * L), (L), (_))
MOCK_LUA_RET(int, lua_gethookcount, (lua_State * L), (L), (_))
MOCK_LUA_RET(int, lua_gethookmask, (lua_State * L), (L), (_))
MOCK_LUA_RET(int, lua_geti, (lua_State * L, int idx, lua_Integer n), (L, idx, n), (_, _, _))
MOCK_LUA_RET(int, lua_getinfo, (lua_State * L, const char *what, lua_Debug *ar), (L, what, ar), (_, _, _))
MOCK_LUA_RET(int, lua_getiuservalue, (lua_State * L, int idx, int n), (L, idx, n), (_, _, _))
MOCK_LUA_RET(const char *, lua_getlocal, (lua_State * L, const lua_Debug *ar, int n), (L, ar, n), (_, _, _))
MOCK_LUA_RET(int, lua_getmetatable, (lua_State * L, int objindex), (L, objindex), (_, _))
MOCK_LUA_RET(int, lua_getstack, (lua_State * L, int level, lua_Debug *ar), (L, level, ar), (_, _, _))
MOCK_LUA_RET(int, lua_gettable, (lua_State * L, int idx), (L, idx), (_, _))
MOCK_LUA_RET(int, lua_gettop, (lua_State * L), (L), (_))
MOCK_LUA_RET(const char *, lua_getupvalue, (lua_State * L, int funcindex, int n), (L, funcindex, n), (_, _, _))
MOCK_LUA_RET(int, lua_iscfunction, (lua_State * L, int idx), (L, idx), (_, _))
MOCK_LUA_RET(int, lua_isinteger, (lua_State * L, int idx), (L, idx), (_, _))
MOCK_LUA_RET(int, lua_isnumber, (lua_State * L, int idx), (L, idx), (_, _))
MOCK_LUA_RET(int, lua_isstring, (lua_State * L, int idx), (L, idx), (_, _))
MOCK_LUA_RET(int, lua_isuserdata, (lua_State * L, int idx), (L, idx), (_, _))
MOCK_LUA_RET(int, lua_isyieldable, (lua_State * L), (L), (_))
MOCK_LUA_VOID(void, lua_len, (lua_State * L, int idx), (L, idx), (_, _))
MOCK_LUA_RET(int, lua_load, (lua_State * L, lua_Reader reader, void *dt, const char *chunkname, const char *mode),
             (L, reader, dt, chunkname, mode), (_, _, _, _, _))
MOCK_LUA_RET(lua_State *, lua_newstate, (lua_Alloc f, void *ud, unsigned seed), (f, ud, seed), (_, _, _))
MOCK_LUA_RET(lua_State *, lua_newthread, (lua_State * L), (L), (_))
MOCK_LUA_RET(void *, lua_newuserdatauv, (lua_State * L, size_t sz, int nuvalue), (L, sz, nuvalue), (_, _, _))
MOCK_LUA_RET(int, lua_next, (lua_State * L, int idx), (L, idx), (_, _))
MOCK_LUA_RET(unsigned, lua_numbertocstring, (lua_State * L, int idx, char *buff), (L, idx, buff), (_, _, _))
MOCK_LUA_RET(int, lua_pcallk, (lua_State * L, int nargs, int nresults, int errfunc, lua_KContext ctx, lua_KFunction k),
             (L, nargs, nresults, errfunc, ctx, k), (_, _, _, _, _, _))
MOCK_LUA_VOID(void, lua_pushboolean, (lua_State * L, int b), (L, b), (_, _))
MOCK_LUA_VOID(void, lua_pushcclosure, (lua_State * L, lua_CFunction fn, int n), (L, fn, n), (_, _, _))
MOCK_LUA_RET(const char *, lua_pushexternalstring,
             (lua_State * L, const char *s, size_t len, lua_Alloc falloc, void *ud), (L, s, len, falloc, ud),
             (_, _, _, _, _))
MOCK_LUA_VOID(void, lua_pushinteger, (lua_State * L, lua_Integer n), (L, n), (_, _))
MOCK_LUA_VOID(void, lua_pushlightuserdata, (lua_State * L, void *p), (L, p), (_, _))
MOCK_LUA_RET(const char *, lua_pushlstring, (lua_State * L, const char *s, size_t len), (L, s, len), (_, _, _))
MOCK_LUA_VOID(void, lua_pushnil, (lua_State * L), (L), (_))
MOCK_LUA_VOID(void, lua_pushnumber, (lua_State * L, lua_Number n), (L, n), (_, _))
MOCK_LUA_RET(const char *, lua_pushstring, (lua_State * L, const char *s), (L, s), (_, _))
MOCK_LUA_RET(int, lua_pushthread, (lua_State * L), (L), (_))
MOCK_LUA_VOID(void, lua_pushvalue, (lua_State * L, int idx), (L, idx), (_, _))
MOCK_LUA_RET(const char *, lua_pushvfstring, (lua_State * L, const char *fmt, va_list argp), (L, fmt, argp), (_, _, _))
MOCK_LUA_RET(int, lua_rawequal, (lua_State * L, int idx1, int idx2), (L, idx1, idx2), (_, _, _))
MOCK_LUA_RET(int, lua_rawget, (lua_State * L, int idx), (L, idx), (_, _))
MOCK_LUA_RET(int, lua_rawgeti, (lua_State * L, int idx, lua_Integer n), (L, idx, n), (_, _, _))
MOCK_LUA_RET(int, lua_rawgetp, (lua_State * L, int idx, const void *p), (L, idx, p), (_, _, _))
MOCK_LUA_RET(lua_Unsigned, lua_rawlen, (lua_State * L, int idx), (L, idx), (_, _))
MOCK_LUA_VOID(void, lua_rawset, (lua_State * L, int idx), (L, idx), (_, _))
MOCK_LUA_VOID(void, lua_rawseti, (lua_State * L, int idx, lua_Integer n), (L, idx, n), (_, _, _))
MOCK_LUA_VOID(void, lua_rawsetp, (lua_State * L, int idx, const void *p), (L, idx, p), (_, _, _))
MOCK_LUA_RET(int, lua_resume, (lua_State * L, lua_State *from, int narg, int *nres), (L, from, narg, nres),
             (_, _, _, _))
MOCK_LUA_VOID(void, lua_rotate, (lua_State * L, int idx, int n), (L, idx, n), (_, _, _))
MOCK_LUA_VOID(void, lua_setallocf, (lua_State * L, lua_Alloc f, void *ud), (L, f, ud), (_, _, _))
MOCK_LUA_VOID(void, lua_setfield, (lua_State * L, int idx, const char *k), (L, idx, k), (_, _, _))
MOCK_LUA_VOID(void, lua_setglobal, (lua_State * L, const char *name), (L, name), (_, _))
MOCK_LUA_VOID(void, lua_sethook, (lua_State * L, lua_Hook func, int mask, int count), (L, func, mask, count),
              (_, _, _, _))
MOCK_LUA_VOID(void, lua_seti, (lua_State * L, int idx, lua_Integer n), (L, idx, n), (_, _, _))
MOCK_LUA_RET(int, lua_setiuservalue, (lua_State * L, int idx, int n), (L, idx, n), (_, _, _))
MOCK_LUA_RET(const char *, lua_setlocal, (lua_State * L, const lua_Debug *ar, int n), (L, ar, n), (_, _, _))
MOCK_LUA_RET(int, lua_setmetatable, (lua_State * L, int objindex), (L, objindex), (_, _))
MOCK_LUA_VOID(void, lua_settable, (lua_State * L, int idx), (L, idx), (_, _))
MOCK_LUA_VOID(void, lua_settop, (lua_State * L, int idx), (L, idx), (_, _))
MOCK_LUA_RET(const char *, lua_setupvalue, (lua_State * L, int funcindex, int n), (L, funcindex, n), (_, _, _))
MOCK_LUA_VOID(void, lua_setwarnf, (lua_State * L, lua_WarnFunction f, void *ud), (L, f, ud), (_, _, _))
MOCK_LUA_RET(int, lua_status, (lua_State * L), (L), (_))
MOCK_LUA_RET(size_t, lua_stringtonumber, (lua_State * L, const char *s), (L, s), (_, _))
MOCK_LUA_RET(int, lua_toboolean, (lua_State * L, int idx), (L, idx), (_, _))
MOCK_LUA_RET(lua_CFunction, lua_tocfunction, (lua_State * L, int idx), (L, idx), (_, _))
MOCK_LUA_VOID(void, lua_toclose, (lua_State * L, int idx), (L, idx), (_, _))
MOCK_LUA_RET(lua_Integer, lua_tointegerx, (lua_State * L, int idx, int *isnum), (L, idx, isnum), (_, _, _))
MOCK_LUA_RET(const char *, lua_tolstring, (lua_State * L, int idx, size_t *len), (L, idx, len), (_, _, _))
MOCK_LUA_RET(lua_Number, lua_tonumberx, (lua_State * L, int idx, int *isnum), (L, idx, isnum), (_, _, _))
MOCK_LUA_RET(const void *, lua_topointer, (lua_State * L, int idx), (L, idx), (_, _))
MOCK_LUA_RET(lua_State *, lua_tothread, (lua_State * L, int idx), (L, idx), (_, _))
MOCK_LUA_RET(void *, lua_touserdata, (lua_State * L, int idx), (L, idx), (_, _))
MOCK_LUA_RET(int, lua_type, (lua_State * L, int idx), (L, idx), (_, _))
MOCK_LUA_RET(const char *, lua_typename, (lua_State * L, int tp), (L, tp), (_, _))
MOCK_LUA_RET(void *, lua_upvalueid, (lua_State * L, int fidx, int n), (L, fidx, n), (_, _, _))
MOCK_LUA_VOID(void, lua_upvaluejoin, (lua_State * L, int fidx1, int n1, int fidx2, int n2), (L, fidx1, n1, fidx2, n2),
              (_, _, _, _, _))
MOCK_LUA_RET(lua_Number, lua_version, (lua_State * L), (L), (_))
MOCK_LUA_VOID(void, lua_warning, (lua_State * L, const char *msg, int tocont), (L, msg, tocont), (_, _, _))
MOCK_LUA_VOID(void, lua_xmove, (lua_State * from, lua_State *to, int n), (from, to, n), (_, _, _))
MOCK_LUA_RET(int, lua_yieldk, (lua_State * L, int nresults, lua_KContext ctx, lua_KFunction k), (L, nresults, ctx, k),
             (_, _, _, _))
MOCK_LUA_RET(int, luaopen_base, (lua_State * L), (L), (_))
MOCK_LUA_RET(int, luaopen_coroutine, (lua_State * L), (L), (_))
MOCK_LUA_RET(int, luaopen_debug, (lua_State * L), (L), (_))
MOCK_LUA_RET(int, luaopen_io, (lua_State * L), (L), (_))
MOCK_LUA_RET(int, luaopen_math, (lua_State * L), (L), (_))
MOCK_LUA_RET(int, luaopen_os, (lua_State * L), (L), (_))
MOCK_LUA_RET(int, luaopen_package, (lua_State * L), (L), (_))
MOCK_LUA_RET(int, luaopen_string, (lua_State * L), (L), (_))
MOCK_LUA_RET(int, luaopen_table, (lua_State * L), (L), (_))
MOCK_LUA_RET(int, luaopen_utf8, (lua_State * L), (L), (_))
